### ISSUE TITLE
Request to reduce image size

### ISSUE THREAD

**Issue by dmowcomber** [sendgrid/aws-env#19]
Could you reduce the image size?

Currently its at 1.2 GB. The only thing I need from the image is the aws-env binary and it would be nice if pulling the image was quicker so we can improve our build speeds.

**Comment by mrobinsn** [comment]
Got it down to 18MB

```
$ docker images | grep aws-env
docker.sendgrid.net/sendgrid/aws-env       1.2.0               d9339fbef907        2 weeks ago            1.2GB
docker.sendgrid.net/sendgrid/aws-env       1.2.1               a57ebca77b29        47 seconds ago      18.8MB
```
